name: Dokka

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    environment:
      name: Production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TIKI SDK Android
        uses: actions/checkout@v4
        with:
          repository: tiki/tiki-sdk-android

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Generate Docs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtml
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './doc/api'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2