name: Publish dokka docs to Github pages

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "dokka"
  cancel-in-progress: true

jobs:
  publish:
    environment:
      name: Production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Generate Docs
        run: ./gradlew dokkaHtml
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './doc/api'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1