name: Publish package to the Maven Central Repository and GitHub Packages

on:
  push:
    branches:
      - github_action

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout TIKI SDK Android"
        uses: actions/checkout@v3
        with:
          repository: tiki/tiki-sdk-android
          path: tiki-sdk-android

      - name: "Checkout TIKI SDK Flutter"
        uses: actions/checkout@v3
        with:
          repository: tiki/tiki-sdk-flutter
          path: tiki-sdk-flutter

      - name: "Setup Dart"
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.2

      - name: "Setup Flutter"
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.4'

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: "Setup Android SDK"
        uses: android-actions/setup-android@v2

      - name: "Patch Flutter"
        run: |
          cd tiki-sdk-android
          git checkout github_action
          cp build-variants.patch /opt/hostedtoolcache/flutter/3.3.4-stable/x64/
          cd /opt/hostedtoolcache/flutter/3.3.4-stable/x64
          git apply build-variants.patch
          cd /home/runner

      - name: "Flutter Pub Get"
        run: |
          cd tiki-sdk-flutter
          git fetch --tags
          latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
          git -c advice.detachedHead=false checkout $latestTag
          flutter pub get
          cd ..

      - name: "Build Android"
        run: |
          cd tiki-sdk-android
          ./gradlew assemble
