name: Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    environment:
      name: Production
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout TIKI SDK Android"
        uses: actions/checkout@v3
        with:
          repository: tiki/tiki-sdk-android

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: "Setup Android SDK"
        uses: android-actions/setup-android@v2

      - name: "Assemble AAR"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble

      - name: "Publish AAR"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_USER: $${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}