name: Publish package to the Maven Central Repository and GitHub Packages

on:
  push:
    branches:
      - github_action

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout TIKI SDK Android"
        uses: actions/checkout@v3
        with:
          repository: tiki/tiki-sdk-android
          path: tiki-sdk-android

      - name: "Checkout TIKI SDK Flutter"
        uses: actions/checkout@v3
        with:
          repository: tiki/tiki-sdk-flutter
          path: tiki-sdk-flutter

      - name: "Setup Dart"
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.2

      - name: "Setup Flutter"
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.4'